console.log("hello world!");
console.log(0123456789);
console.log("nicolly");
x=8+9;
console.log(x);
y=81;
z=9;
t=y+z;
console.log(t);
console.log("o resultado é:",t);
console.log("o outro resultado é:",x);